### ISSUE TITLE
Bug | tfvm purge/reset throws error

### ISSUE THREAD

**Issue by dewhurstwill** [dewhurstwill/tfvm#3]
Investigate and resolve

wdewhurst@WillsLenovo:~/Dev/tfvm$ tfvm purge
Traceback (most recent call last):
  File "tfvm.py", line 12, in <module>
  File "cli_handler.py", line 29, in cli_args
  File "env_handler.py", line 31, in handle_path
UnboundLocalError: local variable 'path_delimiter' referenced before assignment
[7498] Failed to execute script tfvm

**Comment by dewhurstwill** [comment]
Investigate and resolve

wdewhurst@WillsLenovo:~/Dev/tfvm$ tfvm purge
Traceback (most recent call last):
  File "tfvm.py", line 12, in <module>
  File "cli_handler.py", line 29, in cli_args
  File "env_handler.py", line 31, in handle_path
UnboundLocalError: local variable 'path_delimiter' referenced before assignment
[7498] Failed to execute script tfvm

**Comment by dewhurstwill** [comment]
Fixed, please see above PR
